Categories:
  - Multimedia
License: Apache-2.0
AuthorName: Dmitry Dagunts
SourceCode: https://github.com/ddagunts/ScreenCast
IssueTracker: https://github.com/ddagunts/ScreenCast/issues

AutoName: ScreenCast

RepoType: git
Repo: https://github.com/ddagunts/ScreenCast.git

Builds:
  - versionName: '0.3'
    versionCode: 0.3
    commit: v0.3
    subdir: app
    gradle:
      - yes

  - versionName: '0.4.0'
    versionCode: 4
    commit: v0.4.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '0.4.0'
CurrentVersionCode: 4
