Categories:
  - Multimedia
License: Apache-2.0
AuthorName: Dmitry Dagunts
SourceCode: https://github.com/ddagunts/ScreenCast
IssueTracker: https://github.com/ddagunts/ScreenCast/issues

AutoName: ScreenCast

RepoType: git
Repo: https://github.com/ddagunts/ScreenCast.git

Builds:
  - versionName: '0.4.0'
    versionCode: 4
    commit: v0.4.0
    subdir: app
    gradle:
      - yes

  - versionName: '0.4.1'
    versionCode: 5
    commit: v0.4.1
    subdir: app
    gradle:
      - yes

  - versionName: '0.4.3'
    versionCode: 7
    commit: v0.4.3
    subdir: app
    gradle:
      - yes

  - versionName: '0.5.0'
    versionCode: 8
    commit: v0.5.0
    subdir: app
    gradle:
      - yes

  - versionName: '0.5.1'
    versionCode: 9
    commit: v0.5.1
    subdir: app
    gradle:
      - yes

  - versionName: '0.5.2'
    versionCode: 10
    commit: v0.5.2
    subdir: app
    gradle:
      - yes

  - versionName: '0.5.3'
    versionCode: 11
    commit: v0.5.3
    subdir: app
    gradle:
      - yes

  - versionName: '0.5.4'
    versionCode: 12
    commit: v0.5.4
    subdir: app
    gradle:
      - yes

  - versionName: '0.6.0'
    versionCode: 13
    commit: v0.6.0
    subdir: app
    gradle:
      - yes

  - versionName: '0.6.1'
    versionCode: 14
    commit: v0.6.1
    subdir: app
    gradle:
      - yes

  - versionName: '0.7.0'
    versionCode: 15
    commit: v0.7.0
    subdir: app
    gradle:
      - yes

  - versionName: '0.7.1'
    versionCode: 16
    commit: v0.7.1
    subdir: app
    gradle:
      - yes

  - versionName: '0.7.2'
    versionCode: 17
    commit: v0.7.2
    subdir: app
    gradle:
      - yes

  - versionName: '0.8.0'
    versionCode: 18
    commit: v0.8.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '0.8.0'
CurrentVersionCode: 18
