Categories:
  - Multimedia
License: Apache-2.0
AuthorName: Dmitry Dagunts
SourceCode: https://github.com/ddagunts/ScreenCast
IssueTracker: https://github.com/ddagunts/ScreenCast/issues

AutoName: ScreenCast

RepoType: git
Repo: https://github.com/ddagunts/ScreenCast.git

Builds:
  - versionName: '0.4.0'
    versionCode: 4
    commit: v0.4.0
    subdir: app
    gradle:
      - yes

  - versionName: '0.4.1'
    versionCode: 5
    commit: v0.4.1
    subdir: app
    gradle:
      - yes

  - versionName: '0.4.3'
    versionCode: 7
    commit: v0.4.3
    subdir: app
    gradle:
      - yes

  - versionName: '0.5.0'
    versionCode: 8
    commit: v0.5.0
    subdir: app
    gradle:
      - yes

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: '0.5.0'
CurrentVersionCode: 8
